### ISSUE TITLE
Process hangs at 0 of 1 book

### ISSUE THREAD

**Issue by grimble65** [NobahdiAtoll/CRDataManager#2]
I'm trying to update information using this latest release, but it seems to hang up if a book matches the rule.

Attaching the dataman file but have changed the suffix to txt.

[dataman.txt](https://github.com/NobahdiAtoll/CRDataManager/files/517822/dataman.txt)

**Comment by grimble65** [comment]
Further Information:

Seems to work fine with every publisher except DC Comics....?!

**Comment by NobahdiAtoll** [comment]
Gonna need an example dataman.dat I personally haven't been able to reproduce this bug. But I don't doubt it exists.

**Comment by NobahdiAtoll** [comment]
Should be fixed as of latest release
